export const mockHackathons = [
  {
    id: 1,
    name: 'BuildAI 2025',
    description: 'Build the next generation of AI-powered applications that solve real-world problems.',
    status: 'active',
    deadline: '2025-04-15',
    participants: 342,
    teamSize: '2-5',
    mode: 'Online',
    prize: '$10,000',
    featured: true,
    tags: ['AI', 'ML', 'Web'],
  },
  {
    id: 2,
    name: 'GreenTech Sprint',
    description: 'Innovate for sustainability. Create solutions that tackle climate change head-on.',
    status: 'upcoming',
    deadline: '2025-05-20',
    participants: 189,
    teamSize: '1-4',
    mode: 'Hybrid',
    prize: '$5,000',
    featured: false,
    tags: ['ClimaTech', 'IoT'],
  },
  {
    id: 3,
    name: 'HealthHack Global',
    description: 'Reimagine healthcare through technology. Open to all health-tech innovators.',
    status: 'active',
    deadline: '2025-04-28',
    participants: 521,
    teamSize: '2-6',
    mode: 'Online',
    prize: '$15,000',
    featured: true,
    tags: ['HealthTech', 'AI'],
  },
  {
    id: 4,
    name: 'Web3 Builders Cup',
    description: 'Decentralized apps, DeFi, NFTs — build the future of the open web.',
    status: 'upcoming',
    deadline: '2025-06-10',
    participants: 98,
    teamSize: '2-4',
    mode: 'Online',
    prize: '$8,000',
    featured: false,
    tags: ['Web3', 'Blockchain'],
  },
  {
    id: 5,
    name: 'Fintech Foundry',
    description: 'Transform financial services with cutting-edge tech solutions.',
    status: 'completed',
    deadline: '2025-02-28',
    participants: 410,
    teamSize: '2-5',
    mode: 'In-person',
    prize: '$12,000',
    featured: false,
    tags: ['Fintech', 'ML'],
  },
  {
    id: 6,
    name: 'EduTech Challenge',
    description: 'Build the classroom of the future — accessible, engaging, and intelligent.',
    status: 'active',
    deadline: '2025-04-30',
    participants: 267,
    teamSize: '1-3',
    mode: 'Online',
    prize: '$6,000',
    featured: false,
    tags: ['EdTech', 'AI'],
  },
]

export const mockTeamMembers = [
  { id: 1, name: 'Mock User', role: 'Full Stack', avatar: null, isLead: true },
  { id: 2, name: 'Priya Nair', role: 'ML Engineer', avatar: null, isLead: false },
  { id: 3, name: 'Rishi Mehta', role: 'Designer', avatar: null, isLead: false },
  { id: 4, name: 'Anika Patel', role: 'Backend Dev', avatar: null, isLead: false },
]

export const mockLeaderboard = [
  { rank: 1, team: 'ByteBenders', score: 9850, members: 4, badge: 'gold', isYou: false },
  { rank: 2, team: 'CipherPunks', score: 9620, members: 5, badge: 'silver', isYou: false },
  { rank: 3, team: 'NeuralNomads', score: 9410, members: 4, badge: 'bronze', isYou: true },
  { rank: 4, team: 'PixelForge', score: 8990, members: 3, badge: null, isYou: false },
  { rank: 5, team: 'CloudCraft', score: 8750, members: 4, badge: null, isYou: false },
  { rank: 6, team: 'DarkMatter', score: 8510, members: 5, badge: null, isYou: false },
  { rank: 7, team: 'QuantumLeap', score: 8300, members: 3, badge: null, isYou: false },
  { rank: 8, team: 'RoboSquad', score: 8100, members: 4, badge: null, isYou: false },
  { rank: 9, team: 'AlphaWave', score: 7950, members: 5, badge: null, isYou: false },
  { rank: 10, team: 'NexusHub', score: 7720, members: 2, badge: null, isYou: false },
]

export const mockActivity = [
  { id: 1, type: 'submission', text: 'Team submitted "NeuralDash v2"', time: '2h ago', icon: 'upload' },
  { id: 2, type: 'join', text: 'Anika Patel joined your team', time: '5h ago', icon: 'user-plus' },
  { id: 3, type: 'rank', text: 'Your team moved to rank #3', time: '1d ago', icon: 'trending-up' },
  { id: 4, type: 'hackathon', text: 'Joined BuildAI 2025 hackathon', time: '2d ago', icon: 'zap' },
  { id: 5, type: 'comment', text: 'Judge reviewed your submission', time: '3d ago', icon: 'message-circle' },
] 

export const mockSubmissions = [
  {
    id: 1,
    project: 'NeuralDash v2',
    hackathon: 'BuildAI 2025',
    status: 'under_review',
    submittedAt: '2025-03-18',
    score: null,
    techStack: ['React', 'Python', 'TensorFlow'],
    description: 'An intelligent dashboard that adapts to user behavior using real-time ML.',
  },
  {
    id: 2,
    project: 'GreenRoute',
    hackathon: 'GreenTech Sprint',
    status: 'draft',
    submittedAt: null,
    score: null,
    techStack: ['Next.js', 'Node.js', 'Maps API'],
    description: 'Eco-friendly route optimizer for urban logistics.',
  },
  {
    id: 3,
    project: 'HealthScan AI',
    hackathon: 'HealthHack Global',
    status: 'scored',
    submittedAt: '2025-02-25',
    score: 87,
    techStack: ['Python', 'FastAPI', 'PyTorch'],
    description: 'Computer vision model for early disease detection from medical images.',
  },
]

export const mockChartData = [
  { month: 'Oct', score: 3200 },
  { month: 'Nov', score: 4800 },
  { month: 'Dec', score: 4200 },
  { month: 'Jan', score: 6100 },
  { month: 'Feb', score: 7400 },
  { month: 'Mar', score: 9410 },
]

export const mockDeadlines = [
  { name: 'BuildAI 2025', deadline: '2025-04-15', daysLeft: 27, urgency: 'normal' },
  { name: 'HealthHack Global', deadline: '2025-04-28', daysLeft: 40, urgency: 'normal' },
  { name: 'EduTech Challenge', deadline: '2025-04-30', daysLeft: 42, urgency: 'low' },
]
